# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1s6Y7Ucb0wag5gstrtNILC5dRfVZpS_Bl
"""

import streamlit as st
import numpy as np
from PIL import Image

st.title("Système de reconnaissance de véhicule")

upload = st.file_uploader("Téléchargez une image...", type=["jpg", "png"])

if upload:
    img = Image.open(upload)
    st.image(img, width=300)
    st.success("Fonctionnel ! Modèle à intégrer ensuite")

