# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1s6Y7Ucb0wag5gstrtNILC5dRfVZpS_Bl
"""

import streamlit as st
import tensorflow as tf
from PIL import Image
import numpy as np
import time

# Charger le modèle
@st.cache_resource
def load_model():
    return tf.keras.models.load_model('keras_model.h5')

st.set_page_config(layout="wide")
model = load_model()
class_names = ["bus", "camion", "minibus", "suv"]

# Interface
st.title("🚗 Système de reconnaissance de Véhicules")
upload = st.file_uploader("Importer une image...", type=["jpg", "png", "jpeg"])

if upload:
    img = Image.open(upload).convert("RGB")
    st.image(img, width=300)
    
    # Préprocessing
    img = img.resize((224, 224))
    img_array = (np.array(img) / 127.5) - 1
    img_array = np.expand_dims(img_array, axis=0)
    
    # Prédiction
    with st.spinner("Analyse en cours..."):
        pred = model.predict(img_array)
        class_idx = np.argmax(pred[0])
        conf = pred[0][class_idx]
        time.sleep(1)  
    
    st.success(f"**Ce véhicule est un :** {class_names[class_idx]} (Confiance : {conf:.2%})")